environment:
  matrix:
  - Architecture: x64
    Compiler: vs2019
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

install:
- cmd: git submodule update --init --recursive
build: off
build_script:
- ps: >-
    .\PCbuild\prepare_tcltk.bat
test: off
