variables:
  coverage: false

trigger: ['main', '3.10', '3.9', '3.8', '3.7']

jobs:

- job: Windows_CI_Tests
  displayName: Windows CI Tests

  pool:
    vmImage: windows-2019

  strategy:
    matrix:
      win64:
        arch: arm64
        buildOpt: '-p arm64'
        testRunTitle: '$(Build.SourceBranchName)-win64'
        testRunPlatform: win64
    maxParallel: 4

  steps:
  - template: ./windows-steps.yml

  - template: ./windows-layout-steps.yml
    parameters:
      kind: nuget
  - template: ./windows-layout-steps.yml
    parameters:
      kind: embed
  - template: ./windows-layout-steps.yml
    parameters:
      kind: appx
      fulltest: true
